apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: single-nodejs-app
  namespace: aaaa-studio
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: single-nodejs-app
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: single-nodejs-app
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: single-nodejs-app-
      labels:
        build.appstudio.openshift.io/application: single-nodejs-app
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: single-nodejs-app
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: aaaa-studio
    spec:
      params:
      - name: git-url
        value: https://github.com/jduimovich/single-nodejs-app
      - name: output-image
        value: quay.io/jduimovich0/single-nodejs-app:latest-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:13f5d9c921b3f727684a00084037f673a0dc4273
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: single-nodejs-app/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
